### PR TITLE
Formatted code

### PR DESCRIPTION
**Pull request by Zrp200**
* Formatted indention to make the file readable; I couldn't understand it without doing this
* Combined consecutive assignments

### CODE REVIEW

**Comment by Zrp200** [comment]
I found the code _very_ hard to read and understand

**Comment by castwide** [comment]
Personally, I prefer tabs over spaces for indentation. I think it's more convenient for developers to choose their own tab sizes. Unfortunately, the Ruby community appears to disagree as a whole. Every style guide I've seen dictates two spaces instead of tabs, and most editors use two spaces for Ruby by default. Despite my own preference, I decided to go with the consensus.

**Comment by Zrp200** [comment]
I find it easier to use tabs or at least 4 spaces as indention so the difference is more notable

**Comment by Zrp200** [comment]
I can read it with your formatting easily if the code is not complicated

**Comment by peterorme** [comment]
-FWIW I'm with @castwide on this, the Ruby community seems to prefer two spaces... we should stick with that.

**Pull request closed without merging**
